name: "Build"

on:
  push:
    branches: [beta-*.*.*, beta]
  workflow_dispatch:

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v4

    # get branch / tag name
    - name: Get Branch / Tag Name
      id: get_branch
      run: |
        export BRANCH_NAME=$(if [[ ${GITHUB_REF} =~ "refs/tags/" ]]; then echo ${GITHUB_REF/refs\/tags\//}; else echo ${GITHUB_REF/refs\/heads\//}; fi)
        echo $BRANCH_NAME
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT

    # generate the image tag
    - name: Get Image Tag
      id: get_tag
      run: |
        export TARGET_IMAGE_TAG=$(if [ "${{ steps.get_branch.outputs.BRANCH_NAME }}" = "main" ]; then echo "main"; else echo "${{ steps.get_branch.outputs.BRANCH_NAME }}"; fi)
        echo $TARGET_IMAGE_TAG
        echo "TARGET_IMAGE_TAG=${TARGET_IMAGE_TAG}" >> $GITHUB_OUTPUT

    outputs:
      TARGET_IMAGE_TAG: ${{ steps.get_branch.outputs.TARGET_IMAGE_TAG }}
      BRANCH_NAME: ${{ steps.get_branch.outputs.BRANCH_NAME }}


  publish_test:
    needs: get_tags
    name: Publish Test Version - ${{ needs.get_tags.outputs.BRANCH_NAME }}
    if: ${{ needs.get_tags.outputs.BRANCH_NAME != 'main' }}
    uses: homebridge/.github/.github/workflows/npm-publish.yml@latest
    with:
      tag: ${{ needs.get_tags.outputs.BRANCH_NAME }}
      dynamically_adjust_version: true
      npm_version_command: 'pre'
      pre_id: ${{ needs.get_tags.outputs.TARGET_IMAGE_TAG }}
    secrets:
          npm_auth_token: ${{ secrets.npm_token }}

#  publish_release:
#    needs: build

#    name: Publish Release Version
#    if: ${{ BRANCH_NAME == 'main' }}
#    uses: homebridge/.github/.github/workflows/npm-publish.yml@latest
#    with:
#      install_cmd: npm ci
#    secrets:
#      npm_auth_token: ${{ secrets.npm_token }}





